runtime: python311
entrypoint: gunicorn -b :$PORT wsgi:app

instance_class: F4_1G

env_variables:
  FLASK_DEBUG: "1"  # Set to "1" for debugging, "0" for production

handlers:
- url: /.*
  script: auto

